In [15]:
import cv2
from PIL import Image

# Removing backgroung image from hdfc cheque


o_img = Image.open("O-axis_1.jpeg")
o_img = o_img.convert("RGBA")

data_array = o_img.getdata()

newdata = []

for item in data_array:
#     if (item[0] ==  160 and item[1] == 0 and item[2] == 230) or (item[0] ==  160 and item[1] == 0 and item[2] == 215):

     if ((item[0] >= 215 and item[0] <= 240) and (item[1] >= 215 and item[1] <= 240) and (item[0] >= 215 and item[0] <= 240)):
        newdata.append((255, 255, 255, 255))
     else:
        newdata.append(item)
        
o_img.putdata(newdata)
o_img.save("./hdfc.png")


# grey_img = cv2.cvtColor(o_img, cv2.COLOR_BGR2GRAY)
# Image.fromarray(o_img).show()

# _, alpha = cv2.threshold(o_img, 100, 200, cv2.THRESH_BINARY)

# cv2.imshow("Threshold Image",o_img)

# b, g, r = cv2.split(o_img)
# rgba = [b, g, r, alpha]
# dst = cv2.merge(rgba, 2)
# cv2.imwrite("hdfc_b.jpg", dst)
# image1 = cv2.imread("hdfc_b.jpg")

# Image.fromarray(image1).show()

In [11]:
o_img= cv2.imread("O-axis_1.jpeg", flags = cv2.IMREAD_GRAYSCALE)
print(o_img)


[[  0 112   0 ... 253 253 254]
 [  1 118   0 ... 253 253 254]
 [  0 123   3 ... 253 253 254]
 ...
 [  3 109   1 ...  57  58  52]
 [  0 124   0 ...  62  54  50]
 [  3 107   5 ...  56  51  48]]


In [4]:
import cv2
from PIL import Image

# Removing backgroung image from hdfc cheque

o_img= cv2.imread("o_hdfc_e2.jpg", flags = cv2.IMREAD_GRAYSCALE)

o_img


array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [20]:
import cv2
from PIL import Image
import numpy as np

# Removing background image from hdfc cheque
o_img = Image.open(r'C:\pythonproject\ChequeOCR\Backend\hdfc_b.jpg')
o_img = cv2.cvtColor(np.array(o_img), cv2.COLOR_BGR2GRAY)
Image.fromarray(o_img).show()

# print(np.array(o_img))
# o_img = o_img.convert("RGBA")

# data_array = o_img.getdata()

for item in np.array(o_img):
    #     if (item[0] ==  160 and item[1] == 0 and item[2] == 230) or (item[0] ==  160 and item[1] == 0 and item[2] == 215):

    if ((item[0] >= 215 and item[0] <= 255) and (item[1] >= 215 and item[1] <= 255) and (item[0] >= 215 and item[0] <= 255)):
            item[0], item[2], item[3], item[4] = 255, 255, 255, 255        
   
Image.fromarray(o_img).show()

